### ISSUE TITLE
NoSuchMethodError: org.eclipse.jetty.server.Server.setSendServerVersion(Z)V

### ISSUE THREAD

**Issue by debraj-manna** [jadler-mocking/jadler#107] opened 2016-03-05 17:48 UTC
I am trying to use jadler 1.2.0 in a java application. But when ever I am trying to call `initJadler()` from `@Before` in a junit test it I am getting the below error:-

```
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Server.setSendServerVersion(Z)V
	at net.jadler.stubbing.server.jetty.JettyStubHttpServer.<init>(JettyStubHttpServer.java:33)
	at net.jadler.stubbing.server.jetty.JettyStubHttpServer.<init>(JettyStubHttpServer.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.jadler.Jadler.getJettyServer(Jadler.java:718)
	at net.jadler.Jadler.initJadler(Jadler.java:618)
	at com.jabong.orchestratorservice.adapter.order.OrderMainAppTest.setUp(OrderMainAppTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I have added the following dependency:-
```
		<dependency>
			<groupId>net.jadler</groupId>
			<artifactId>jadler-all</artifactId>
			<version>1.2.0</version>
			<scope>test</scope>
		</dependency>
```

I am using `junit-4.12`

**Comment by jandudek** [comment] 2016-03-06 11:32
Hi @debraj-manna , let's check this. Could you please paste a result of `mvn dependency:tree` here? There may be some clash of libraries here.

**Comment by debraj-manna-jabong** [comment] 2016-03-07 09:57
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ basecomponent ---
[INFO] com.jabong.orchestratorservice:basecomponent:bundle:0.0.1-SNAPSHOT
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- net.jadler:jadler-all:jar:1.2.0:test
[INFO] |  +- net.jadler:jadler-core:jar:1.2.0:test
[INFO] |  |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  |  +- commons-io:commons-io:jar:2.4:test
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:test
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.1:test
[INFO] |  +- net.jadler:jadler-jetty:jar:1.2.0:test
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:8.1.11.v20130520:provided
[INFO] |  |  |  +- org.eclipse.jetty:jetty-continuation:jar:8.1.11.v20130520:provided
[INFO] |  |  |  \- org.eclipse.jetty:jetty-http:jar:8.1.11.v20130520:provided
[INFO] |  |  \- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:provided
[INFO] |  \- net.jadler:jadler-junit:jar:1.2.0:test
[INFO] +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] +- com.github.arnabk:java-dogstatsd-client:jar:1.0.1:compile
[INFO] |  \- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] +- org.json:json:jar:20151123:compile
[INFO] +- javax.xml.bind:jaxb-api:jar:2.2.11:compile
[INFO] +- mysql:mysql-connector-java:jar:5.1.6:compile
[INFO] +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  \- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] +- org.apache.camel:camel-jdbc:jar:2.16.1:provided
[INFO] |  +- com.sun.xml.bind:jaxb-core:jar:2.2.11:provided
[INFO] |  \- com.sun.xml.bind:jaxb-impl:jar:2.2.11:provided
[INFO] +- org.apache.camel:camel-jetty:jar:2.16.1:provided
[INFO] |  \- org.apache.camel:camel-jetty9:jar:2.16.1:provided
[INFO] |     +- org.eclipse.jetty:jetty-servlet:jar:9.2.11.v20150529:provided
[INFO] |     +- org.eclipse.jetty:jetty-security:jar:9.2.11.v20150529:provided
[INFO] |     +- org.eclipse.jetty:jetty-servlets:jar:9.2.11.v20150529:provided
[INFO] |     |  +- org.eclipse.jetty:jetty-util:jar:9.2.11.v20150529:provided
[INFO] |     |  \- org.eclipse.jetty:jetty-io:jar:9.2.11.v20150529:provided
[INFO] |     +- org.eclipse.jetty:jetty-client:jar:9.2.11.v20150529:provided
[INFO] |     +- org.eclipse.jetty:jetty-jmx:jar:9.2.11.v20150529:provided
[INFO] |     \- org.apache.camel:camel-jetty-common:jar:2.16.1:provided
[INFO] +- org.apache.camel:camel-http4:jar:2.16.1:provided
[INFO] |  +- org.apache.camel:camel-http-common:jar:2.16.1:provided
[INFO] |  |  \- org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0:provided
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.1:provided
[INFO] |     +- org.apache.httpcomponents:httpcore:jar:4.4.3:provided
[INFO] |     +- commons-logging:commons-logging:jar:1.2:provided
[INFO] |     \- commons-codec:commons-codec:jar:1.9:provided
[INFO] +- org.apache.camel:camel-core:jar:2.16.1:provided
[INFO] +- org.apache.camel:camel-test:jar:2.16.1:test
[INFO] +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.12:compile
[INFO] \- log4j:log4j:jar:1.2.17:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.559 s
[INFO] Finished at: 2016-03-07T15:26:40+05:30
[INFO] Final Memory: 18M/214M
```

**Comment by debraj-manna** [comment] 2016-03-08 06:06
Let me know if you need any more info.

**Comment by jandudek** [comment] 2016-03-13 03:24
I checked the dependency tree you posted here and I was able to reproduce the problem. The root cause is a clash of jetty libraries. While Jadler uses Jetty8, there is a Jetty9 artifact on your classpath as well. And it seems the `Server` class from Jetty8 gets overwritten by the one from Jetty9 (which doesn't provide the `setSendServerVersion` anymore.

There are two ways to fix this problem. Is it really necessary to have the Jetty9 library on your classpath during the test? If not just try to remove it and everything should work just fine. If yes there is an option to run Jadler with an alternative (non-Jetty) server, please read how to do it in https://github.com/jadler-mocking/jadler/wiki/Using-the-Alternative-Stub-Server-Implementation.

**Comment by debraj-manna** [comment] 2016-03-13 17:54
Thanks Jan for looking into this. Actually I tried using the alternate
JdkStubHttpServer as mentioned in the link you shared. But it was giving me
some other error.

I will try to share with you the error.

**Comment by jandudek** [comment] 2016-03-19 01:15
Ok, i'm closing this issue. Please file another issue for the JdkStubHttpServer error if it's still relevant.

**Closed by jandudek** 2016-03-19 01:15 UTC
